const config = {
  baseUrl: "http://localhost:9000",
  port: 9000,
  tb: {
    student: "students",
    register: "Registers",
    account: "Accounts",
    class: "classes",
    relationship: "Relationship",
    parent: "Parents",
    levels: "levels",
    sysllabus: "syllabus",
    approves: "approves",
    addmission: "admission_periods",
    teacher: "teachers",
    classManager: "class_managers",
    managerRole: "class_manager_roles",
    classMembers: "class_members",
    registerNotes: "register_notes",
    managerRoles: "class_manager_roles",
    teacher_specialization: "teacher_specializations",
    specialization: "specializations",
    teacher_certificates: "teacher_certificates",
    certificates: "certificates",
    meals: "meals",
    dishes: "dishes",
    news: "news",
    slideshow: "slideshow",
  },
};

module.exports = config;
